.. # Use http://b64.io/ to encode any image to base64. Then replace `/` with
   # `%2F` and `+` with `%2B` (or use http://meyerweb.com/eric/tools/dencoder/).
   # Beware that `?logo=data:image/png;base64,` must also be converted to
   # percent encoding so that the URL is properly parsed.

.. # Sourcecode link to GitHub
.. |SHIELD:svg:pyVersioning-github| image:: https://img.shields.io/badge/Paebbels-pyVersioning-323131?longCache=true&style=flat-square&longCache=true&logo=GitHub
   :alt: Sourcecode on GitHub
   :height: 22
   :target: https://GitHub.com/Paebbels/pyVersioning
.. |SHIELD:png:pyVersioning-github| image:: https://raster.shields.io/badge/Paebbels-pyVersioning-323131?longCache=true&style=flat-square&longCache=true&logo=GitHub
   :alt: Sourcecode on GitHub
   :height: 22
   :target: https://GitHub.com/Paebbels/pyVersioning

.. # Sourcecode license
.. |SHIELD:svg:pyVersioning-src-license| image:: https://img.shields.io/pypi/l/pyVersioning?longCache=true&style=flat-square&logo=Apache&label=code
   :alt: Code license
   :height: 22
   :target: Code-License.html
.. |SHIELD:png:pyVersioning-src-license| image:: https://img.shields.io/pypi/l/pyVersioning?longCache=true&style=flat-square&logo=Apache&label=code
   :alt: Code license
   :height: 22
   :target: https://GitHub.com/Paebbels/pyVersioning/blob/main/LICENSE.md

.. # GitHub tag
.. |SHIELD:svg:pyVersioning-tag| image:: https://img.shields.io/github/v/tag/Paebbels/pyVersioning?longCache=true&style=flat-square&logo=GitHub&include_prereleases
   :alt: GitHub tag (latest SemVer incl. pre-release
   :height: 22
   :target: https://GitHub.com/Paebbels/pyVersioning/tags
.. |SHIELD:png:pyVersioning-tag| image:: https://raster.shields.io/github/v/tag/Paebbels/pyVersioning?longCache=true&style=flat-square&logo=GitHub&include_prereleases
   :alt: GitHub tag (latest SemVer incl. pre-release
   :height: 22
   :target: https://GitHub.com/Paebbels/pyVersioning/tags

.. # GitHub release date
.. |SHIELD:svg:pyVersioning-date| image:: https://img.shields.io/github/release-date/Paebbels/pyVersioning?longCache=true&style=flat-square&logo=GitHub
   :alt: GitHub release date
   :height: 22
   :target: https://GitHub.com/Paebbels/pyVersioning/releases
.. |SHIELD:png:pyVersioning-date| image:: https://raster.shields.io/github/release-date/Paebbels/pyVersioning?longCache=true&style=flat-square&logo=GitHub
   :alt: GitHub release date
   :height: 22
   :target: https://GitHub.com/Paebbels/pyVersioning/releases

.. # GitHub/Libraries dependent projects
.. |SHIELD:svg:pyVersioning-lib-dep| image:: https://img.shields.io/librariesio/dependent-repos/pypi/pyVersioning?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Dependent repos (via libraries.io)
   :height: 22
   :target: https://GitHub.com/Paebbels/pyVersioning/network/dependents
.. |SHIELD:png:pyVersioning-lib-dep| image:: https://raster.shields.io/librariesio/dependent-repos/pypi/pyVersioning?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Dependent repos (via libraries.io)
   :height: 22
   :target: https://GitHub.com/Paebbels/pyVersioning/network/dependents

.. # GHA test and coverage
.. |SHIELD:svg:pyVersioning-gha-test| image:: https://img.shields.io/github/actions/workflow/status/Paebbels/pyVersioning/Pipeline.yml?branch=main&longCache=true&style=flat-square&label=Build%20and%20Test&logo=GitHub%20Actions&logoColor=FFFFFF
   :alt: GitHub Workflow - Build and Test Status
   :height: 22
   :target: https://GitHub.com/Paebbels/pyVersioning/actions/workflows/Pipeline.yml
.. |SHIELD:png:pyVersioning-gha-test| image:: https://raster.shields.io/github/actions/workflow/status/Paebbels/pyVersioning/Pipeline.yml?branch=main&longCache=true&style=flat-square&label=Build%20and%20Test&logo=GitHub%20Actions&logoColor=FFFFFF
   :alt: GitHub Workflow - Build and Test Status
   :height: 22
   :target: https://GitHub.com/Paebbels/pyVersioning/actions/workflows/Pipeline.yml

.. # Codacy - quality
.. |SHIELD:svg:pyVersioning-codacy-quality| image:: https://img.shields.io/codacy/grade/fda25870e76849f48bbf7415fb6e9ccf?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Quality
   :height: 22
   :target: https://www.codacy.com/gh/Paebbels/pyVersioning
.. |SHIELD:png:pyVersioning-codacy-quality| image:: https://raster.shields.io/codacy/grade/fda25870e76849f48bbf7415fb6e9ccf?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Quality
   :height: 22
   :target: https://www.codacy.com/gh/Paebbels/pyVersioning

.. # Codacy - coverage
.. |SHIELD:svg:pyVersioning-codacy-coverage| image:: https://img.shields.io/codacy/coverage/fda25870e76849f48bbf7415fb6e9ccf?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Line Coverage
   :height: 22
   :target: https://www.codacy.com/gh/Paebbels/pyVersioning
.. |SHIELD:png:pyVersioning-codacy-coverage| image:: https://raster.shields.io/codacy/coverage/fda25870e76849f48bbf7415fb6e9ccf?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Line Coverage
   :height: 22
   :target: https://www.codacy.com/gh/Paebbels/pyVersioning

.. # Codecov - coverage
.. |SHIELD:svg:pyVersioning-codecov-coverage| image:: https://img.shields.io/codecov/c/github/Paebbels/pyVersioning?longCache=true&style=flat-square&logo=Codecov
   :alt: Codecov - Branch Coverage
   :height: 22
   :target: https://codecov.io/gh/Paebbels/pyVersioning
.. |SHIELD:png:pyVersioning-codecov-coverage| image:: https://raster.shields.io/codecov/c/github/Paebbels/pyVersioning?longCache=true&style=flat-square&logo=Codecov
   :alt: Codecov - Branch Coverage
   :height: 22
   :target: https://codecov.io/gh/Paebbels/pyVersioning

.. # Libraries - source rank
.. |SHIELD:svg:pyVersioning-lib-rank| image:: https://img.shields.io/librariesio/sourcerank/pypi/pyVersioning?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io SourceRank
   :height: 22
   :target: https://libraries.io/github/Paebbels/pyVersioning/sourcerank
.. |SHIELD:png:pyVersioning-lib-rank| image:: https://raster.shields.io/librariesio/sourcerank/pypi/pyVersioning?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io SourceRank
   :height: 22
   :target: https://libraries.io/github/Paebbels/pyVersioning/sourcerank

.. # PyPI tag
.. |SHIELD:svg:pyVersioning-pypi-tag| image:: https://img.shields.io/pypi/v/pyVersioning?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Tag
   :height: 22
   :target: https://pypi.org/project/pyVersioning/
.. |SHIELD:png:pyVersioning-pypi-tag| image:: https://raster.shields.io/pypi/v/pyVersioning?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Tag
   :height: 22
   :target: https://pypi.org/project/pyVersioning/

.. # PyPI project status
.. |SHIELD:svg:pyVersioning-pypi-status| image:: https://img.shields.io/pypi/status/pyVersioning?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Status
   :height: 22
.. |SHIELD:png:pyVersioning-pypi-status| image:: https://raster.shields.io/pypi/status/pyVersioning?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Status
   :height: 22

.. # PyPI Python versions
.. |SHIELD:svg:pyVersioning-pypi-python| image:: https://img.shields.io/pypi/pyversions/pyVersioning?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Python Version
   :height: 22
.. |SHIELD:png:pyVersioning-pypi-python| image:: https://raster.shields.io/pypi/pyversions/pyVersioning?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Python Version
   :height: 22

.. # Libraries - status
.. |SHIELD:svg:pyVersioning-lib-status| image:: https://img.shields.io/librariesio/release/pypi/pyVersioning?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io status for latest release
   :height: 22
   :target: https://libraries.io/github/Paebbels/pyVersioning
.. |SHIELD:png:pyVersioning-lib-status| image:: https://raster.shields.io/librariesio/release/pypi/pyVersioning?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io status for latest release
   :height: 22
   :target: https://libraries.io/github/Paebbels/pyVersioning

.. # Documentation license
.. |SHIELD:svg:pyVersioning-doc-license| image:: https://img.shields.io/badge/doc-CC--BY%204.0-green?longCache=true&style=flat-square&logo=CreativeCommons&logoColor=fff
   :alt: Documentation License
   :height: 22
   :target: License.html
.. |SHIELD:png:pyVersioning-doc-license| image:: https://raster.shields.io/badge/doc-CC--BY%204.0-green?longCache=true&style=flat-square&logo=CreativeCommons&logoColor=fff
   :alt: Documentation License
   :height: 22
   :target: https://GitHub.com/Paebbels/pyVersioning/blob/main/doc/License.rst

.. # GHPages - read now
.. |SHIELD:svg:pyVersioning-ghp-doc| image:: https://img.shields.io/website?longCache=true&style=flat-square&label=Paebbels.github.io%2FpyVersioning&logo=GitHub&logoColor=fff&up_color=blueviolet&up_message=Read%20now%20%E2%9E%9A&url=https%3A%2F%2FPaebbels.github.io%2FpyVersioning%2Findex.html
   :alt: Documentation - Read Now!
   :height: 22
   :target: https://Paebbels.github.io/pyVersioning/
.. |SHIELD:png:pyVersioning-ghp-doc| image:: https://raster.shields.io/website?longCache=true&style=flat-square&label=Paebbels.github.io%2FpyVersioning&logo=GitHub&logoColor=fff&up_color=blueviolet&up_message=Read%20now%20%E2%9E%9A&url=https%3A%2F%2FPaebbels.github.io%2FpyVersioning%2Findex.html
   :alt: Documentation - Read Now!
   :height: 22
   :target: https://Paebbels.github.io/pyVersioning/

.. # Gitter
.. |SHIELD:svg:pyVersioning-gitter| image:: https://img.shields.io/badge/chat-on%20gitter-4db797?longCache=true&style=flat-square&logo=gitter&logoColor=e8ecef
   :alt: Documentation License
   :height: 22
   :target: https://gitter.im/hdl/community
.. |SHIELD:png:pyVersioning-gitter| image:: https://raster.shields.io/badge/chat-on%20gitter-4db797?longCache=true&style=flat-square&logo=gitter&logoColor=e8ecef
   :alt: Documentation License
   :height: 22
   :target: https://gitter.im/hdl/community
